{{- if .Values.rbac.create }}
{{- if .Values.rbac.clusterScope }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "maop-operator.fullname" . }}
  labels:
    {{- include "maop-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "maop-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "maop-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "maop-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maop-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "maop-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "maop-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
