{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "maop-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maop-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook-server
      port: {{ .Values.service.port }}
      targetPort: webhook-server
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "maop-operator.selectorLabels" . | nindent 4 }}
{{- end }}
