"""Agent subpackage.

Agent 生命周期、subagent、编排核心（DAG/phase/runtime）、LLM 集成、
工具管理、插件、hook。

Modules:
    agent_lifecycle, agent_memory, agent_performance, agent_proxy,
    agent_registry, agent_repair, agent_scanner, agent_evolution,
    subagent, subagent_db, subagent_delegation (shim), subagent_lifecycle,
    subagent_manager, analyzer, phases, runtime, protocol, a2a,
    llm_provider, chat_engine, react_loop, tool_manager, tool_schema,
    tool_audit, conversation, project_context, context_compressor,
    function_call, output_parser, state_classifier, human_proxy,
    worktree, hook_manager, plugin, capability_matcher

Note:
    P0-2 (2026-08-07): subagent_delegation 已合并到 subagent_lifecycle。
    SubagentManager 是 SubAgentManager 的别名。subagent_delegation 模块
    保留为重定向 shim。
"""
from __future__ import annotations

import importlib
import warnings

__all__ = [
    "FREQUENT_CAP_THRESHOLD",
    "HIGH_FAILURE_RATE_THRESHOLD",
    "HIGH_LATENCY_THRESHOLD_MS",
    "KNOWN_AGENTS",
    "MAX_RECORDS_PER_TYPE",
    "MEMORY_TYPES",
    "PREF_ADJUSTMENT_THRESHOLD",
    "REQUIRED_COLUMNS",
    "SCHEMA_SQL",
    "SUBAGENT_DB_NAME",
    "TASK_KEYWORD_MAP",
    "A2ACard",
    "A2AClient",
    "A2AManager",
    "A2AMessage",
    "A2AResponse",
    "A2ATaskState",
    "AdapterConfig",
    "AdapterStatus",
    "AgentAdapter",
    "AgentConfig",
    "AgentEvolution",
    "AgentLifecycle",
    "AgentLifecycleManager",
    "AgentMemory",
    "AgentMessage",
    "AgentPerformanceTracker",
    "AgentProxy",
    "AgentRegistry",
    "AgentRepair",
    "AgentResult",
    "AgentRole",
    "AgentScanner",
    "AgentScore",
    "AgentSource",
    "AgentState",
    "AgentStats",
    "AgentStatus",
    "AgentTreeNode",
    "AnalysisResult",
    "AnthropicProvider",
    "ApprovalRequest",
    "BaseLLMProvider",
    "BaseRuntime",
    "BranchInfo",
    "BranchStatus",
    "CapabilityMatcher",
    "ChatEngine",
    "ChatMessage",
    "ChatRequest",
    "ChatResponse",
    "CheckpointInfo",
    "ClassificationResult",
    "Complexity",
    "CompressionResult",
    "ContainerRuntime",
    "ContentPart",
    "ContextCompressor",
    "ContextSection",
    "ContextWindow",
    "ConversationManager",
    "DagProgressEmitter",
    "DependencyDAG",
    "DiagnosisResult",
    "DiffItem",
    "DiffReport",
    "EvolutionResult",
    "EvolutionSuggestion",
    "ExecutionResult",
    "ExecutionStrategy",
    "FallbackResult",
    "FunctionCallBridge",
    "HealthCheckResult",
    "HealthStatus",
    "HookDef",
    "HookManager",
    "HookPhase",
    "HookResult",
    "HookTriggerStats",
    "HookType",
    "HumanProxy",
    "HumanProxyConfig",
    "IsolatedRuntime",
    "KnownAgentDef",
    "LLMProviderFactory",
    "LLMResponse",
    "LifecycleEvent",
    "LocalRuntime",
    "MatchScore",
    "MatcherConfig",
    "MergeResult",
    "MergeStrategy",
    "Message",
    "MessageRole",
    "ModelConfig",
    # DAG progress emitter (v4.5.0 — streaming DAG progress push)
    "NodeStatus",
    "NodeStatusEvent",
    "OllamaProvider",
    "OpenAICompatibleProvider",
    "OutputParser",
    "ParseResult",
    "PhaseContext",
    "PhaseResult",
    "PluginInfo",
    "PluginManager",
    "PluginManifest",
    "PluginSandbox",
    "PluginState",
    "ProjectContext",
    "ProjectInfo",
    "ProtocolDef",
    "ProtocolMessage",
    "ProtocolRegistry",
    "ProviderConfig",
    "ReactConfig",
    "ReactLoop",
    "ReactPhase",
    "ReactResult",
    "ReactStep",
    "RegisteredAgent",
    "RepairResult",
    "RuntimeConfig",
    "RuntimeInfo",
    "RuntimeType",
    "SandboxViolation",
    "ScannedAgent",
    "StateTransition",
    "SubAgentManager",
    "SubTask",
    "SubagentInfo",
    "SubagentManager",
    "T",
    "TaskState",
    "TaskStateClassifier",
    "ToolAuditEntry",
    "ToolAuditLog",
    "ToolAuditStats",
    "ToolCall",
    "ToolCallResult",
    "ToolDef",
    "ToolManager",
    "ToolProvider",
    "ToolSchemaDef",
    "ToolSchemaGenerator",
    "TranscriptEntry",
    "WorktreeManager",
    "analyze",
    "create_a2a_router",
    "create_runtime",
    "get_hook_manager",
    "get_subagent_db_path",
    "init_subagent_db",
    "logger",
    "migrate_legacy_subagent_db",
]

# 符号 → 子模块名映射（惰性加载用，含私有符号）
_SYMBOL_TO_MODULE: dict[str, str] = {
    # 注: 多个子模块均导出同名符号（如 logger），
    # 按字典构造语义仅最后一个映射生效，与重构前运行时行为一致。
    "_A2A_DDL": "delegation.a2a",
    "A2ACard": "delegation.a2a",
    "A2AMessage": "delegation.a2a",
    "A2AResponse": "delegation.a2a",
    "A2ATaskState": "delegation.a2a",
    "A2AManager": "delegation.a2a",
    "A2AClient": "delegation.a2a",
    "create_a2a_router": "delegation.a2a",
    "EvolutionSuggestion": "evolution.agent_evolution",
    "EvolutionResult": "evolution.agent_evolution",
    "HIGH_LATENCY_THRESHOLD_MS": "evolution.agent_evolution",
    "HIGH_FAILURE_RATE_THRESHOLD": "evolution.agent_evolution",
    "FREQUENT_CAP_THRESHOLD": "evolution.agent_evolution",
    "PREF_ADJUSTMENT_THRESHOLD": "evolution.agent_evolution",
    "AgentEvolution": "evolution.agent_evolution",
    "AgentState": "lifecycle.agent_lifecycle",
    "StateTransition": "lifecycle.agent_lifecycle",
    "_VALID_TRANSITIONS": "lifecycle.agent_lifecycle",
    "AgentLifecycle": "lifecycle.agent_lifecycle",
    "AgentLifecycleManager": "lifecycle.agent_lifecycle",
    "MEMORY_TYPES": "memory_ctx.agent_memory",
    "MAX_RECORDS_PER_TYPE": "memory_ctx.agent_memory",
    "AgentMemory": "memory_ctx.agent_memory",
    "AgentStats": "lifecycle.agent_performance",
    "AgentScore": "lifecycle.agent_performance",
    "_PERFORMANCE_DDL": "lifecycle.agent_performance",
    "AgentPerformanceTracker": "lifecycle.agent_performance",
    "AdapterStatus": "delegation.agent_proxy",
    "AdapterConfig": "delegation.agent_proxy",
    "AgentAdapter": "delegation.agent_proxy",
    "_ADAPTER_DDL": "delegation.agent_proxy",
    "AgentProxy": "delegation.agent_proxy",
    "HealthStatus": "lifecycle.agent_registry",
    "HealthCheckResult": "lifecycle.agent_registry",
    "RegisteredAgent": "lifecycle.agent_registry",
    "AgentRegistry": "lifecycle.agent_registry",
    "DiagnosisResult": "lifecycle.agent_repair",
    "RepairResult": "lifecycle.agent_repair",
    "_KNOWN_INSTALLERS": "lifecycle.agent_repair",
    "_PIP_PACKAGE_MAP": "lifecycle.agent_repair",
    "AgentRepair": "lifecycle.agent_repair",
    "AgentSource": "lifecycle.agent_scanner",
    "ScannedAgent": "lifecycle.agent_scanner",
    "KnownAgentDef": "lifecycle.agent_scanner",
    "KNOWN_AGENTS": "lifecycle.agent_scanner",
    "AgentScanner": "lifecycle.agent_scanner",
    "MatchScore": "tools.capability_matcher",
    "MatcherConfig": "tools.capability_matcher",
    "TASK_KEYWORD_MAP": "tools.capability_matcher",
    "CapabilityMatcher": "tools.capability_matcher",
    "SUBAGENT_DB_NAME": "delegation.subagent_db",
    "SCHEMA_SQL": "delegation.subagent_db",
    "_ANCILLARY_SQL": "delegation.subagent_db",
    "REQUIRED_COLUMNS": "delegation.subagent_db",
    "_NON_MIGRATABLE_COLUMNS": "delegation.subagent_db",
    "_NULLABLE_IN_NEW_SCHEMA": "delegation.subagent_db",
    "get_subagent_db_path": "delegation.subagent_db",
    "init_subagent_db": "delegation.subagent_db",
    "_has_not_null_conflict": "delegation.subagent_db",
    "_rebuild_subagents_table": "delegation.subagent_db",
    "migrate_legacy_subagent_db": "delegation.subagent_db",
    "SubagentInfo": "delegation.subagent_lifecycle",
    "AgentMessage": "delegation.subagent_lifecycle",
    "AgentTreeNode": "delegation.subagent_lifecycle",
    "SubagentManager": "delegation.subagent_lifecycle",
    "AgentRole": "delegation.subagent_lifecycle",
    "AgentStatus": "delegation.subagent_lifecycle",
    "AgentConfig": "delegation.subagent_lifecycle",
    "AgentResult": "delegation.subagent_lifecycle",
    "TranscriptEntry": "delegation.subagent_lifecycle",
    "SubAgentManager": "delegation.subagent_lifecycle",
    "Complexity": "analyzer",
    "ExecutionStrategy": "analyzer",
    "SubTask": "analyzer",
    "DependencyDAG": "analyzer",
    "AnalysisResult": "analyzer",
    "_RULE_PATTERNS": "analyzer",
    "_CONJUNCTION_PATTERN": "analyzer",
    "_STEP_PATTERN": "analyzer",
    "_rule_decompose": "analyzer",
    "_classify_category": "analyzer",
    "_estimate_effort": "analyzer",
    "_config_enrich": "analyzer",
    "_DEPENDENCY_KEYWORDS": "analyzer",
    "_RISK_KEYWORDS": "analyzer",
    "_rule_based_semantic_analyze": "analyzer",
    "_LLM_DECOMP_KEYS": "analyzer",
    "_VALID_RISK_LEVELS": "analyzer",
    "_build_llm_decomp_prompt": "analyzer",
    "_parse_llm_decomp": "analyzer",
    "_semantic_analyze": "analyzer",
    "_select_strategy": "analyzer",
    "_complexity_level": "analyzer",
    "analyze": "analyzer",
    "PhaseContext": "evolution.phases",
    "PhaseResult": "evolution.phases",
    "_WIN_BUILTINS": "lifecycle.runtime",
    "_resolve_cmd": "lifecycle.runtime",
    "RuntimeType": "lifecycle.runtime",
    "RuntimeConfig": "lifecycle.runtime",
    "ExecutionResult": "lifecycle.runtime",
    "RuntimeInfo": "lifecycle.runtime",
    "BaseRuntime": "lifecycle.runtime",
    "LocalRuntime": "lifecycle.runtime",
    "IsolatedRuntime": "lifecycle.runtime",
    "ContainerRuntime": "lifecycle.runtime",
    "_RUNTIME_MAP": "lifecycle.runtime",
    "create_runtime": "lifecycle.runtime",
    "MessageRole": "llm_chat.conversation",
    "Message": "llm_chat.conversation",
    "ContextWindow": "llm_chat.conversation",
    "ConversationManager": "llm_chat.conversation",
    "ToolProvider": "llm_chat.function_call",
    "ToolCall": "llm_chat.function_call",
    "FunctionCallBridge": "llm_chat.function_call",
    "ApprovalRequest": "delegation.human_proxy",
    "HumanProxyConfig": "delegation.human_proxy",
    "HumanProxy": "delegation.human_proxy",
    "T": "llm_chat.output_parser",
    "ParseResult": "llm_chat.output_parser",
    "OutputParser": "llm_chat.output_parser",
    "ProjectInfo": "memory_ctx.project_context",
    "ProjectContext": "memory_ctx.project_context",
    "TaskState": "lifecycle.state_classifier",
    "ClassificationResult": "lifecycle.state_classifier",
    "_BLOCKED_PATTERNS": "lifecycle.state_classifier",
    "_FAILED_PATTERNS": "lifecycle.state_classifier",
    "_WORKING_PATTERNS": "lifecycle.state_classifier",
    "TaskStateClassifier": "lifecycle.state_classifier",
    "BranchStatus": "memory_ctx.worktree",
    "MergeStrategy": "memory_ctx.worktree",
    "BranchInfo": "memory_ctx.worktree",
    "MergeResult": "memory_ctx.worktree",
    "DiffItem": "memory_ctx.worktree",
    "DiffReport": "memory_ctx.worktree",
    "CheckpointInfo": "memory_ctx.worktree",
    "_WORKTREE_DDL": "memory_ctx.worktree",
    "WorktreeManager": "memory_ctx.worktree",
    "ProtocolDef": "plugins_hooks.protocol",
    "ProtocolMessage": "plugins_hooks.protocol",
    "ProtocolRegistry": "plugins_hooks.protocol",
    "_check_type": "plugins_hooks.protocol",
    "_fail_open_default": "plugins_hooks.hook_manager",
    "LifecycleEvent": "plugins_hooks.hook_manager",
    "HookType": "plugins_hooks.hook_manager",
    "HookPhase": "plugins_hooks.hook_manager",
    "HookDef": "plugins_hooks.hook_manager",
    "HookResult": "plugins_hooks.hook_manager",
    "HookTriggerStats": "plugins_hooks.hook_manager",
    "HookManager": "plugins_hooks.hook_manager",
    "_hook_manager": "plugins_hooks.hook_manager",
    "get_hook_manager": "plugins_hooks.hook_manager",
    "PluginState": "plugins_hooks.plugin",
    "PluginManifest": "plugins_hooks.plugin",
    "_BLOCKED_BUILTINS": "plugins_hooks.plugin",
    "_SAFE_BUILTINS_ADDITIONS": "plugins_hooks.plugin",
    "_DEFAULT_ALLOWED_IMPORTS": "plugins_hooks.plugin",
    "SandboxViolation": "plugins_hooks.plugin",
    "PluginSandbox": "plugins_hooks.plugin",
    "PluginInfo": "plugins_hooks.plugin",
    "PluginManager": "plugins_hooks.plugin",
    "ToolAuditEntry": "tools.tool_audit",
    "ToolAuditStats": "tools.tool_audit",
    "_TOOL_AUDIT_DDL": "tools.tool_audit",
    "ToolAuditLog": "tools.tool_audit",
    "_get_maop_version": "tools.tool_manager",
    "_parse_version": "tools.tool_manager",
    "_is_version_compatible": "tools.tool_manager",
    "ToolDef": "tools.tool_manager",
    "ToolCallResult": "tools.tool_manager",
    "ToolManager": "tools.tool_manager",
    "_PYTHON_TYPE_TO_JSON": "tools.tool_schema",
    "ToolSchemaDef": "tools.tool_schema",
    "ToolSchemaGenerator": "tools.tool_schema",
    "ContentPart": "llm_chat.chat_engine",
    "ChatMessage": "llm_chat.chat_engine",
    "ChatRequest": "llm_chat.chat_engine",
    "ChatResponse": "llm_chat.chat_engine",
    "ChatEngine": "llm_chat.chat_engine",
    "_sse_event": "llm_chat.chat_engine",
    "LLMResponse": "llm_chat.llm_provider",
    "FallbackResult": "llm_chat.llm_provider",
    "ProviderConfig": "llm_chat.llm_provider",
    "ModelConfig": "llm_chat.llm_provider",
    "BaseLLMProvider": "llm_chat.llm_provider",
    "OpenAICompatibleProvider": "llm_chat.llm_provider",
    "AnthropicProvider": "llm_chat.llm_provider",
    "OllamaProvider": "llm_chat.llm_provider",
    "LLMProviderFactory": "llm_chat.llm_provider",
    "_is_error_response": "llm_chat.llm_provider",
    "_record_cost": "llm_chat.llm_provider",
    "logger": "llm_chat.react_loop",
    "ReactPhase": "llm_chat.react_loop",
    "ReactStep": "llm_chat.react_loop",
    "ReactResult": "llm_chat.react_loop",
    "ReactConfig": "llm_chat.react_loop",
    "ReactLoop": "llm_chat.react_loop",
    "ContextSection": "llm_chat.context_compressor",
    "CompressionResult": "llm_chat.context_compressor",
    "ContextCompressor": "llm_chat.context_compressor",
    # DAG progress emitter (v4.5.0)
    "NodeStatus": "dag.dag_progress_emitter",
    "NodeStatusEvent": "dag.dag_progress_emitter",
    "DagProgressEmitter": "dag.dag_progress_emitter",
}


def __getattr__(name: str):
    """惰性加载子模块符号，避免循环导入。"""
    if name in _SYMBOL_TO_MODULE:
        mod_name = _SYMBOL_TO_MODULE[name]
        mod = importlib.import_module(f".{mod_name}", __name__)
        value = getattr(mod, name)
        globals()[name] = value  # 缓存，下次直接访问
        # P2-5: ProjectContext 从顶层包 re-export 已废弃（v5.0.0 起），
        # 应直接从 maop.core.agent.memory_ctx.project_context 导入。
        # 计划在 v6.0.0 移除 re-export。因 globals() 缓存，仅首次访问时触发。
        if name == "ProjectContext":
            warnings.warn(
                "Importing ProjectContext from maop.core.agent is deprecated since v5.0.0 "
                "and will be removed in v6.0.0. "
                "Use 'from maop.core.agent.memory_ctx.project_context import ProjectContext' instead.",
                DeprecationWarning,
                stacklevel=2,
            )
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
