"""Monitoring subpackage.

可观测性、指标、成本追踪、预算守卫。

Modules:
    monitoring, otel, cost_tracker, timeseries, budget_guard
"""
from __future__ import annotations

import importlib

__all__ = [
    "DEFAULT_PRICING",
    "MAOP_ACTIVE_AGENTS",
    "MAOP_CIRCUIT_BREAKER_STATE",
    "MAOP_DELEGATIONS_FAILED",
    "MAOP_DELEGATIONS_SUCCESS",
    "MAOP_DELEGATIONS_TOTAL",
    "MAOP_DELEGATION_DURATION",
    "MAOP_MCP_CACHE_EVICTION_TOTAL",
    "MAOP_MCP_CACHE_HIT_TOTAL",
    "MAOP_MCP_CACHE_MISS_TOTAL",
    "MAOP_MCP_CALLS_TOTAL",
    "MAOP_MCP_CALL_ALLOWED_TOTAL",
    "MAOP_MCP_CALL_AUDITED_TOTAL",
    "MAOP_MCP_CALL_DENIED_TOTAL",
    "MAOP_MCP_CALL_DURATION_SECONDS",
    "MAOP_MCP_CALL_ERRORS_TOTAL",
    "MAOP_MCP_CONCURRENT_ACTIVE",
    "MAOP_MCP_HEALTH_CHECK_TOTAL",
    "MAOP_MCP_RATE_LIMITED_TOTAL",
    "MAOP_MCP_SERVERS_CONNECTED",
    "MAOP_MEMORY_ENTRIES",
    "MAOP_MODEL_SELECTION_LOAD_AWARE",
    "MAOP_MODEL_SELECTION_QUOTA_REJECTED",
    "MAOP_PRIORITY_QUEUE_SIZE",
    "MAOP_QUEUE_PENDING",
    "MAOP_ROUTE_DECISION_MODE",
    "MAOP_ROUTING_DECISION_DURATION_MS",
    "MAOP_ROUTING_DECISION_TOTAL",
    "MAOP_STICKY_SESSION_ACTIVE",
    "MAOP_STICKY_SESSION_HIT",
    "MAOP_STICKY_SESSION_MISS",
    "MAOP_TASK_DEADLINE_SECONDS",
    "MAOP_TASK_PREEMPTION_TOTAL",
    "MAOP_TASK_PRIORITY_DISTRIBUTION",
    "MAOP_TASK_SLA_TIER_DISTRIBUTION",
    "MAOP_TASK_SLA_VIOLATION_TOTAL",
    "BudgetGuard",
    "BudgetStatus",
    "CostEntry",
    "CostSummary",
    "CostTracker",
    "Counter",
    "DataPoint",
    "Gauge",
    "Histogram",
    "JsonLogFormatter",
    "MetricsCollector",
    "ModelPricing",
    "RetentionPolicy",
    "StructuredLogger",
    "TimeSeriesQuery",
    "TimeSeriesStats",
    "TimeSeriesStore",
    "extract_trace_context",
    "get_cost_tracker",
    "get_priority_wait_histogram",
    "get_tracer",
    "inject_trace_context",
    "is_enabled",
    "logger",
    "metrics",
    "setup_json_logging",
    "setup_provider",
    "span",
]

# 符号 → 子模块名映射（惰性加载用，含私有符号）
_SYMBOL_TO_MODULE: dict[str, str] = {
    # 注: 多个子模块均导出同名符号（如 logger），
    # 按字典构造语义仅最后一个映射生效，与重构前运行时行为一致。
    "_BUDGET_DDL": "maop.core.budget_guard",
    "BudgetGuard": "maop.core.budget_guard",
    "CostEntry": "maop.core.cost_tracker",
    "CostSummary": "maop.core.cost_tracker",
    "BudgetStatus": "maop.core.cost_tracker",
    "ModelPricing": "maop.core.cost_tracker",
    "DEFAULT_PRICING": "maop.core.cost_tracker",
    "CostTracker": "maop.core.cost_tracker",
    "_cost_tracker_instance": "maop.core.cost_tracker",
    "get_cost_tracker": "maop.core.cost_tracker",
    "JsonLogFormatter": "monitoring",
    "_STANDARD_LOGRECORD_ATTRS": "monitoring",
    "setup_json_logging": "monitoring",
    "StructuredLogger": "monitoring",
    "_MAX_LABEL_CARDINALITY": "monitoring",
    "_OVERFLOW_KEY": "monitoring",
    "_bounded_key": "monitoring",
    "Counter": "monitoring",
    "Gauge": "monitoring",
    "Histogram": "monitoring",
    "MetricsCollector": "monitoring",
    "metrics": "monitoring",
    "MAOP_DELEGATIONS_TOTAL": "monitoring",
    "MAOP_DELEGATIONS_SUCCESS": "monitoring",
    "MAOP_DELEGATIONS_FAILED": "monitoring",
    "MAOP_DELEGATION_DURATION": "monitoring",
    "MAOP_ACTIVE_AGENTS": "monitoring",
    "MAOP_MEMORY_ENTRIES": "monitoring",
    "MAOP_QUEUE_PENDING": "monitoring",
    "MAOP_CIRCUIT_BREAKER_STATE": "monitoring",
    "MAOP_TASK_DEADLINE_SECONDS": "monitoring",
    "MAOP_TASK_SLA_VIOLATION_TOTAL": "monitoring",
    "MAOP_TASK_PRIORITY_DISTRIBUTION": "monitoring",
    "MAOP_TASK_SLA_TIER_DISTRIBUTION": "monitoring",
    "MAOP_ROUTE_DECISION_MODE": "monitoring",
    "MAOP_TASK_PREEMPTION_TOTAL": "monitoring",
    "MAOP_PRIORITY_QUEUE_SIZE": "monitoring",
    "_MAOP_PRIORITY_WAIT_HISTOGRAMS": "monitoring",
    "get_priority_wait_histogram": "monitoring",
    "MAOP_MODEL_SELECTION_QUOTA_REJECTED": "monitoring",
    "MAOP_MODEL_SELECTION_LOAD_AWARE": "monitoring",
    "MAOP_STICKY_SESSION_HIT": "monitoring",
    "MAOP_STICKY_SESSION_MISS": "monitoring",
    "MAOP_STICKY_SESSION_ACTIVE": "monitoring",
    "MAOP_MCP_CALL_AUDITED_TOTAL": "monitoring",
    "MAOP_MCP_CALL_DENIED_TOTAL": "monitoring",
    "MAOP_MCP_CALL_ALLOWED_TOTAL": "monitoring",
    "MAOP_MCP_CALLS_TOTAL": "monitoring",
    "MAOP_MCP_CALL_DURATION_SECONDS": "monitoring",
    "MAOP_MCP_SERVERS_CONNECTED": "monitoring",
    "MAOP_MCP_CALL_ERRORS_TOTAL": "monitoring",
    "MAOP_MCP_HEALTH_CHECK_TOTAL": "monitoring",
    "MAOP_MCP_CACHE_HIT_TOTAL": "monitoring",
    "MAOP_MCP_CACHE_MISS_TOTAL": "monitoring",
    "MAOP_MCP_CACHE_EVICTION_TOTAL": "monitoring",
    "MAOP_MCP_CONCURRENT_ACTIVE": "monitoring",
    "MAOP_MCP_RATE_LIMITED_TOTAL": "monitoring",
    "MAOP_ROUTING_DECISION_TOTAL": "monitoring",
    "MAOP_ROUTING_DECISION_DURATION_MS": "monitoring",
    "_OTELE_AVAILABLE": "otel",
    "is_enabled": "otel",
    "get_tracer": "otel",
    "span": "otel",
    "setup_provider": "otel",
    "inject_trace_context": "otel",
    "extract_trace_context": "otel",
    "_NoopTracer": "otel",
    "_NoopSpan": "otel",
    "logger": "timeseries",
    "DataPoint": "timeseries",
    "TimeSeriesQuery": "timeseries",
    "TimeSeriesStats": "timeseries",
    "RetentionPolicy": "timeseries",
    "TimeSeriesStore": "timeseries",
}


def __getattr__(name: str):
    """惰性加载子模块符号，避免循环导入。"""
    if name in _SYMBOL_TO_MODULE:
        mod_name = _SYMBOL_TO_MODULE[name]
        if mod_name.startswith("."):
            mod = importlib.import_module(mod_name, __name__)
        else:
            mod = importlib.import_module(mod_name)
        value = getattr(mod, name)
        globals()[name] = value  # 缓存，下次直接访问
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
