"""Tests for the License Management backend (PRD: license-management).

Covers:
  - LicenseManager business logic (create, validate, revoke, renew, update, delete)
  - Audit log recording and querying
  - Pydantic request models (validation constraints)
  - API router endpoints (with admin auth + FeatureFlag gating)
  - SQLite persistence (default backend)

The tests use an in-memory Ed25519 keypair (auto-generated by LicenseManager
when no private_key_path is given) and an isolated SQLite DB under tmp_path.
"""

from __future__ import annotations

import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from types import SimpleNamespace

import pytest

# P2 修复：无条件 skip 改为 import 条件化 —— maop.enterprise 可导入
# （企业版）时才真正运行测试；个人版（未安装）时才跳过。
try:
    import maop.enterprise  # noqa: F401
except ImportError:
    pytest.skip(reason="maop.enterprise 未发布", allow_module_level=True)

from maop.enterprise.license_manager import (
    LicenseCreateRequest,
    LicenseManager,
    LicenseNotFoundError,
    LicenseRecord,
    LicenseRenewRequest,
    LicenseRevokeRequest,
    LicenseUpdateRequest,
    LicenseValidateRequest,
)

# ── Fixtures ──────────────────────────────────────────────────────


@pytest.fixture
def manager(tmp_path: Path) -> LicenseManager:
    """LicenseManager with an in-memory keypair and isolated SQLite DB."""
    db_path = tmp_path / "data" / "test_licenses.db"
    db_path.parent.mkdir(parents=True, exist_ok=True)
    return LicenseManager(db_path=db_path)


def _future_iso(days: int = 365) -> str:
    """Return an ISO datetime string `days` days in the future."""
    return (datetime.now(timezone.utc) + timedelta(days=days)).strftime("%Y-%m-%d")


def _past_iso(days: int = 30) -> str:
    """Return an ISO date string `days` days in the past."""
    return (datetime.now(timezone.utc) - timedelta(days=days)).strftime("%Y-%m-%d")


def _make_admin_request() -> SimpleNamespace:
    """Fake FastAPI Request with admin roles on state."""
    return SimpleNamespace(state=SimpleNamespace(auth_roles=["admin"]))


def _make_non_admin_request() -> SimpleNamespace:
    """Fake FastAPI Request with non-admin roles on state."""
    return SimpleNamespace(state=SimpleNamespace(auth_roles=["viewer"]))


# ── Pydantic request models ───────────────────────────────────────


class TestPydanticModels:
    def test_license_create_request_minimal(self):
        req = LicenseCreateRequest(customer="ACME", expires_at="2027-12-31")
        assert req.customer == "ACME"
        assert req.expires_at == "2027-12-31"
        assert req.max_users is None
        assert req.features == []

    def test_license_create_request_full(self):
        req = LicenseCreateRequest(
            customer="ACME",
            expires_at="2027-12-31T23:59:59Z",
            max_users=100,
            fingerprint="abc123",
            features=["rbac", "audit_log"],
            issued_by="admin",
            notes="Annual license",
        )
        assert req.max_users == 100
        assert req.features == ["rbac", "audit_log"]

    def test_license_create_request_rejects_empty_customer(self):
        with pytest.raises(Exception):  # noqa: B017
            LicenseCreateRequest(customer="", expires_at="2027-12-31")

    def test_license_create_request_rejects_invalid_max_users(self):
        with pytest.raises(Exception):  # noqa: B017
            LicenseCreateRequest(customer="ACME", expires_at="2027-12-31", max_users=0)

    def test_license_update_request_all_none(self):
        req = LicenseUpdateRequest()
        assert req.customer is None
        assert req.max_users is None

    def test_license_renew_request(self):
        req = LicenseRenewRequest(new_expires_at="2028-12-31")
        assert req.new_expires_at == "2028-12-31"
        assert req.actor == ""

    def test_license_revoke_request_defaults(self):
        req = LicenseRevokeRequest()
        assert req.reason == ""
        assert req.actor == ""

    def test_license_validate_request(self):
        req = LicenseValidateRequest(license_key="MAOP-ENT-xxx.yyy")
        assert req.license_key == "MAOP-ENT-xxx.yyy"


# ── LicenseManager business logic ─────────────────────────────────


class TestLicenseManagerCreate:
    def test_create_license_returns_record(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME Corp", expires_at=_future_iso(365))
        assert isinstance(rec, LicenseRecord)
        assert rec.customer == "ACME Corp"
        assert rec.status == "active"
        assert rec.license_key.startswith("MAOP-ENT-")
        assert "." in rec.license_key
        assert rec.license_id  # non-empty UUID

    def test_create_license_with_optional_fields(self, manager: LicenseManager):
        rec = manager.create_license(
            customer="ACME",
            expires_at=_future_iso(365),
            max_users=100,
            fingerprint="fp-abc",
            features=["rbac", "sso"],
            issued_by="admin",
            notes="test",
        )
        assert rec.max_users == 100
        assert rec.fingerprint == "fp-abc"
        assert rec.features == ["rbac", "sso"]
        assert rec.issued_by == "admin"
        assert rec.notes == "test"

    def test_create_license_persists_to_db(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        loaded = manager.get_license(rec.license_id)
        assert loaded.customer == "ACME"
        assert loaded.license_key == rec.license_key

    def test_create_license_records_audit(self, manager: LicenseManager):
        rec = manager.create_license(
            customer="ACME", expires_at=_future_iso(365), issued_by="alice"
        )
        logs = manager.get_audit_logs(license_id=rec.license_id)
        assert len(logs) == 1
        assert logs[0].action == "created"
        assert logs[0].actor == "alice"
        assert "ACME" in logs[0].detail


class TestLicenseManagerValidate:
    def test_validate_valid_license(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        result = manager.validate_license(rec.license_key)
        assert result["valid"] is True
        assert result["reason"] == "ok"
        assert result["info"]["customer"] == "ACME"

    def test_validate_expired_license(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_past_iso(30))
        result = manager.validate_license(rec.license_key)
        assert result["valid"] is False
        assert result["reason"] == "expired"

    def test_validate_grace_period_license(self, manager: LicenseManager):
        # Expired 2 days ago — within the 7-day grace period.
        expires_dt = datetime.now(timezone.utc) - timedelta(days=2)
        rec = manager.create_license(customer="ACME", expires_at=expires_dt.isoformat())
        result = manager.validate_license(rec.license_key)
        assert result["valid"] is True
        assert result["reason"] == "in_grace_period"

    def test_validate_revoked_license(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        manager.revoke_license(rec.license_id, reason="policy violation")
        result = manager.validate_license(rec.license_key)
        assert result["valid"] is False
        assert "revoked" in result["reason"]

    def test_validate_tampered_signature(self, manager: LicenseManager):
        import base64

        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        # Flip a bit in the signature portion.
        payload_b64, sig_b64 = rec.license_key[len("MAOP-ENT-"):].rsplit(".", 1)
        sig = bytearray(base64.urlsafe_b64decode(sig_b64 + "=="))
        sig[0] ^= 0x01
        tampered_sig = base64.urlsafe_b64encode(bytes(sig)).rstrip(b"=").decode("ascii")
        tampered = f"MAOP-ENT-{payload_b64}.{tampered_sig}"
        result = manager.validate_license(tampered)
        assert result["valid"] is False
        assert "signature_invalid" in result["reason"]

    def test_validate_malformed_key(self, manager: LicenseManager):
        result = manager.validate_license("not-a-license")
        assert result["valid"] is False
        assert "signature_invalid" in result["reason"]

    def test_validate_empty_key(self, manager: LicenseManager):
        result = manager.validate_license("")
        assert result["valid"] is False


class TestLicenseManagerRevoke:
    def test_revoke_license(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        revoked = manager.revoke_license(rec.license_id, reason="test", actor="admin")
        assert revoked.status == "revoked"
        assert revoked.revoked_at is not None
        assert revoked.revoked_reason == "test"

    def test_revoke_license_records_audit(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        manager.revoke_license(rec.license_id, reason="policy", actor="admin")
        logs = manager.get_audit_logs(license_id=rec.license_id)
        actions = [entry.action for entry in logs]
        assert "revoked" in actions

    def test_revoke_already_revoked_is_idempotent(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        manager.revoke_license(rec.license_id, reason="first")
        second = manager.revoke_license(rec.license_id, reason="second")
        assert second.status == "revoked"
        # Reason from the first revocation is preserved.
        assert second.revoked_reason == "first"

    def test_revoke_nonexistent_raises(self, manager: LicenseManager):
        with pytest.raises(LicenseNotFoundError):
            manager.revoke_license("nonexistent-uuid")


class TestLicenseManagerRenew:
    def test_renew_license_extends_expiry(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(30))
        original_expiry = rec.expires_at
        renewed = manager.renew_license(
            rec.license_id, new_expires_at=_future_iso(365), actor="admin"
        )
        assert renewed.expires_at > original_expiry
        assert renewed.status == "active"
        # New key is generated.
        assert renewed.license_key != rec.license_key

    def test_renew_license_records_audit(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(30))
        manager.renew_license(rec.license_id, new_expires_at=_future_iso(365))
        logs = manager.get_audit_logs(license_id=rec.license_id)
        actions = [entry.action for entry in logs]
        assert "renewed" in actions

    def test_renew_revoked_license_reactivates(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(30))
        manager.revoke_license(rec.license_id, reason="temp")
        renewed = manager.renew_license(rec.license_id, new_expires_at=_future_iso(365))
        assert renewed.status == "active"
        assert renewed.revoked_at is None

    def test_renew_nonexistent_raises(self, manager: LicenseManager):
        with pytest.raises(LicenseNotFoundError):
            manager.renew_license("nonexistent", new_expires_at=_future_iso(365))


class TestLicenseManagerUpdate:
    def test_update_metadata(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        updated = manager.update_license(
            rec.license_id, customer="ACME Corp", notes="updated note"
        )
        assert updated.customer == "ACME Corp"
        assert updated.notes == "updated note"

    def test_update_features(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        updated = manager.update_license(rec.license_id, features=["rbac", "sso", "audit"])
        assert updated.features == ["rbac", "sso", "audit"]

    def test_update_no_changes_returns_same(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        updated = manager.update_license(rec.license_id)
        assert updated.customer == rec.customer

    def test_update_nonexistent_raises(self, manager: LicenseManager):
        with pytest.raises(LicenseNotFoundError):
            manager.update_license("nonexistent", customer="X")


class TestLicenseManagerDelete:
    def test_delete_license(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        assert manager.delete_license(rec.license_id) is True
        with pytest.raises(LicenseNotFoundError):
            manager.get_license(rec.license_id)

    def test_delete_nonexistent_raises(self, manager: LicenseManager):
        with pytest.raises(LicenseNotFoundError):
            manager.delete_license("nonexistent")


class TestLicenseManagerList:
    def test_list_empty(self, manager: LicenseManager):
        assert manager.list_licenses() == []

    def test_list_all(self, manager: LicenseManager):
        manager.create_license(customer="A", expires_at=_future_iso(365))
        manager.create_license(customer="B", expires_at=_future_iso(365))
        licenses = manager.list_licenses()
        assert len(licenses) == 2

    def test_list_filter_by_status(self, manager: LicenseManager):
        rec1 = manager.create_license(customer="A", expires_at=_future_iso(365))
        rec2 = manager.create_license(customer="B", expires_at=_future_iso(365))
        manager.revoke_license(rec2.license_id)
        active = manager.list_licenses(status="active")
        revoked = manager.list_licenses(status="revoked")
        assert len(active) == 1
        assert active[0].license_id == rec1.license_id
        assert len(revoked) == 1
        assert revoked[0].license_id == rec2.license_id


class TestAuditLog:
    def test_audit_log_records_all_actions(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        manager.revoke_license(rec.license_id, actor="alice")
        manager.renew_license(rec.license_id, new_expires_at=_future_iso(365), actor="bob")
        logs = manager.get_audit_logs(license_id=rec.license_id)
        actions = [entry.action for entry in logs]
        assert "created" in actions
        assert "revoked" in actions
        assert "renewed" in actions

    def test_audit_log_filter_by_action(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        manager.revoke_license(rec.license_id)
        created_logs = manager.get_audit_logs(license_id=rec.license_id, action="created")
        assert len(created_logs) == 1
        assert created_logs[0].action == "created"

    def test_audit_log_limit_offset(self, manager: LicenseManager):
        rec = manager.create_license(customer="ACME", expires_at=_future_iso(365))
        manager.revoke_license(rec.license_id)
        manager.renew_license(rec.license_id, new_expires_at=_future_iso(365))
        # 3 actions total: created, revoked, renewed
        all_logs = manager.get_audit_logs(license_id=rec.license_id, limit=100)
        assert len(all_logs) == 3
        limited = manager.get_audit_logs(license_id=rec.license_id, limit=2)
        assert len(limited) == 2
        offset = manager.get_audit_logs(license_id=rec.license_id, limit=10, offset=2)
        assert len(offset) == 1


class TestLicenseRecordProperties:
    def test_is_expired(self):
        rec = LicenseRecord(
            license_id="x", customer="A", issued_at=0,
            expires_at=time.time() - 100, license_key="k",
        )
        assert rec.is_expired is True

    def test_is_not_expired(self):
        rec = LicenseRecord(
            license_id="x", customer="A", issued_at=0,
            expires_at=time.time() + 100, license_key="k",
        )
        assert rec.is_expired is False

    def test_is_in_grace_period(self):
        rec = LicenseRecord(
            license_id="x", customer="A", issued_at=0,
            expires_at=time.time() - 86400, license_key="k",  # 1 day ago
        )
        assert rec.is_in_grace_period is True

    def test_is_not_in_grace_period_after_grace(self):
        rec = LicenseRecord(
            license_id="x", customer="A", issued_at=0,
            expires_at=time.time() - 8 * 86400, license_key="k",  # 8 days ago
        )
        assert rec.is_in_grace_period is False

    def test_is_revoked(self):
        rec = LicenseRecord(
            license_id="x", customer="A", issued_at=0,
            expires_at=time.time() + 100, license_key="k",
            status="revoked",
        )
        assert rec.is_revoked is True
        assert rec.is_active is False

    def test_is_active(self):
        rec = LicenseRecord(
            license_id="x", customer="A", issued_at=0,
            expires_at=time.time() + 100, license_key="k",
        )
        assert rec.is_active is True


# ── API Router tests ──────────────────────────────────────────────


class TestLicensesRouter:
    """Test the FastAPI router endpoints with mocked admin auth."""

    @pytest.fixture(autouse=True)
    def _enable_feature(self, monkeypatch: pytest.MonkeyPatch) -> None:
        """Force LICENSE_MANAGEMENT feature on and edition to enterprise."""
        from maop.config.edition import (
            Edition,
            FeatureFlag,
            set_edition,
            set_feature_override,
        )
        set_edition(Edition.ENTERPRISE)
        set_feature_override(FeatureFlag.LICENSE_MANAGEMENT, True)
        # Reset the router-level manager singleton so each test gets a fresh one.
        import maop.dashboard.routers.licenses as router_mod
        router_mod._license_manager = None
        yield
        set_feature_override(FeatureFlag.LICENSE_MANAGEMENT, False)

    @pytest.fixture
    def admin_request(self) -> SimpleNamespace:
        return _make_admin_request()

    @pytest.fixture
    def non_admin_request(self) -> SimpleNamespace:
        return _make_non_admin_request()

    @pytest.mark.asyncio
    async def test_list_empty(self, admin_request):
        from maop.dashboard.routers.licenses import list_licenses
        result = await list_licenses(admin_request, status="")
        assert result["status"] == "ok"
        assert result["count"] == 0
        assert result["licenses"] == []

    @pytest.mark.asyncio
    async def test_create_and_list(self, admin_request):
        from maop.dashboard.routers.licenses import create_license, list_licenses
        body = {"customer": "ACME Corp", "expires_at": _future_iso(365)}
        result = await create_license(admin_request, body)
        assert result["status"] == "ok"
        license_id = result["license"]["license_id"]
        # List should now contain one license.
        listing = await list_licenses(admin_request, status="")
        assert listing["count"] == 1
        assert listing["licenses"][0]["license_id"] == license_id

    @pytest.mark.asyncio
    async def test_create_and_get(self, admin_request):
        from maop.dashboard.routers.licenses import create_license, get_license
        body = {"customer": "ACME", "expires_at": _future_iso(365), "max_users": 50}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        got = await get_license(license_id, admin_request)
        assert got["status"] == "ok"
        assert got["license"]["customer"] == "ACME"
        assert got["license"]["max_users"] == 50

    @pytest.mark.asyncio
    async def test_get_nonexistent_returns_404(self, admin_request):
        from fastapi.responses import JSONResponse

        from maop.dashboard.routers.licenses import get_license
        result = await get_license("nonexistent", admin_request)
        # handle_api_errors catches HTTPException and returns JSONResponse.
        assert isinstance(result, JSONResponse)
        assert result.status_code == 404

    @pytest.mark.asyncio
    async def test_validate_endpoint(self, admin_request):
        from maop.dashboard.routers.licenses import create_license, validate_license
        body = {"customer": "ACME", "expires_at": _future_iso(365)}
        created = await create_license(admin_request, body)
        key = created["license"]["license_key"]
        result = await validate_license(admin_request, {"license_key": key})
        assert result["status"] == "ok"
        assert result["validation"]["valid"] is True

    @pytest.mark.asyncio
    async def test_revoke_endpoint(self, admin_request):
        from maop.dashboard.routers.licenses import create_license, revoke_license
        body = {"customer": "ACME", "expires_at": _future_iso(365)}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        result = await revoke_license(license_id, admin_request, {"reason": "test", "actor": "admin"})
        assert result["status"] == "ok"
        assert result["license"]["status"] == "revoked"

    @pytest.mark.asyncio
    async def test_renew_endpoint(self, admin_request):
        from maop.dashboard.routers.licenses import create_license, renew_license
        body = {"customer": "ACME", "expires_at": _future_iso(30)}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        original_key = created["license"]["license_key"]
        result = await renew_license(
            license_id, admin_request,
            {"new_expires_at": _future_iso(365), "actor": "admin"},
        )
        assert result["status"] == "ok"
        assert result["license"]["license_key"] != original_key

    @pytest.mark.asyncio
    async def test_update_endpoint(self, admin_request):
        from maop.dashboard.routers.licenses import create_license, update_license
        body = {"customer": "ACME", "expires_at": _future_iso(365)}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        result = await update_license(
            license_id, admin_request,
            {"customer": "ACME Corp", "notes": "updated"},
        )
        assert result["status"] == "ok"
        assert result["license"]["customer"] == "ACME Corp"
        assert result["license"]["notes"] == "updated"

    @pytest.mark.asyncio
    async def test_delete_endpoint(self, admin_request):
        from fastapi.responses import JSONResponse

        from maop.dashboard.routers.licenses import create_license, delete_license, get_license
        body = {"customer": "ACME", "expires_at": _future_iso(365)}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        result = await delete_license(license_id, admin_request)
        assert result["status"] == "ok"
        assert result["deleted"] is True
        # Subsequent get should return 404 JSONResponse.
        result = await get_license(license_id, admin_request)
        assert isinstance(result, JSONResponse)
        assert result.status_code == 404

    @pytest.mark.asyncio
    async def test_audit_endpoint(self, admin_request):
        from maop.dashboard.routers.licenses import (
            create_license,
            get_license_audit,
            revoke_license,
        )
        body = {"customer": "ACME", "expires_at": _future_iso(365)}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        await revoke_license(license_id, admin_request, {"reason": "test"})
        result = await get_license_audit(license_id, admin_request, limit=100, offset=0)
        assert result["status"] == "ok"
        assert result["count"] == 2  # created + revoked
        actions = [e["action"] for e in result["audit_logs"]]
        assert "created" in actions
        assert "revoked" in actions

    @pytest.mark.asyncio
    async def test_list_audit_endpoint(self, admin_request):
        from maop.dashboard.routers.licenses import (
            create_license,
            list_audit_logs,
            revoke_license,
        )
        body = {"customer": "ACME", "expires_at": _future_iso(365)}
        created = await create_license(admin_request, body)
        license_id = created["license"]["license_id"]
        await revoke_license(license_id, admin_request, {"reason": "x"})
        result = await list_audit_logs(
            admin_request, license_id="", action="", limit=100, offset=0,
        )
        assert result["status"] == "ok"
        assert result["count"] >= 2

    @pytest.mark.asyncio
    async def test_non_admin_gets_403(self, non_admin_request):
        from fastapi.responses import JSONResponse

        from maop.dashboard.routers.licenses import list_licenses
        result = await list_licenses(non_admin_request, status="")
        # require_admin raises HTTPException(403); handle_api_errors
        # converts it to a JSONResponse with status_code=403.
        assert isinstance(result, JSONResponse)
        assert result.status_code == 403

    @pytest.mark.asyncio
    async def test_feature_disabled_returns_404(self, admin_request, monkeypatch):
        from fastapi.responses import JSONResponse

        from maop.config.edition import FeatureFlag, set_feature_override
        set_feature_override(FeatureFlag.LICENSE_MANAGEMENT, False)
        from maop.dashboard.routers.licenses import list_licenses
        result = await list_licenses(admin_request, status="")
        assert isinstance(result, JSONResponse)
        assert result.status_code == 404
        # Re-enable for the autouse cleanup.
        set_feature_override(FeatureFlag.LICENSE_MANAGEMENT, True)


# ── Datetime parsing ──────────────────────────────────────────────


class TestDatetimeParsing:
    def test_parse_yyyy_mm_dd(self):
        dt = LicenseManager._parse_datetime("2027-12-31")
        assert dt.year == 2027
        assert dt.month == 12
        assert dt.day == 31
        assert dt.hour == 23
        assert dt.minute == 59
        assert dt.second == 59
        assert dt.tzinfo == timezone.utc

    def test_parse_iso_with_z(self):
        dt = LicenseManager._parse_datetime("2027-12-31T10:00:00Z")
        assert dt.hour == 10
        assert dt.tzinfo == timezone.utc

    def test_parse_iso_with_offset(self):
        dt = LicenseManager._parse_datetime("2027-12-31T10:00:00+02:00")
        assert dt.tzinfo == timezone.utc
        # 10:00 +02:00 == 08:00 UTC
        assert dt.hour == 8

    def test_parse_datetime_object(self):
        original = datetime(2027, 12, 31, 10, 0, 0, tzinfo=timezone.utc)
        dt = LicenseManager._parse_datetime(original)
        assert dt == original

    def test_parse_naive_datetime_assumed_utc(self):
        original = datetime(2027, 12, 31, 10, 0, 0)  # noqa: DTZ001
        dt = LicenseManager._parse_datetime(original)
        assert dt.tzinfo == timezone.utc
        assert dt.hour == 10