"""Reliability subpackage.

可靠性模式（熔断/缓存/队列/限流）+ 事件总线 + 流式基础设施 +
配置变更 + 文件安全 + 自愈 + 服务注册。

Modules:
    circuit_breaker, cache, message_queue, worker_pool,
    preemptable_worker_pool, priority_queue, rate_limiter, event_bus,
    streaming, error_ledger, error_schema, pipeline_checkpoint,
    config_mutator, change_tracker, safe_writer, filelock, log_rotate,
    self_heal, services, cache_guard
"""
from __future__ import annotations

import importlib

__all__ = [
    "logger",
    "K",
    "V",
    "SENTINEL_NULL",
    "is_sentinel_null",
    "CacheEntry",
    "CacheStats",
    "LRUCache",
    "get_cache",
    "CacheGuardConfig",
    "CacheGuardStats",
    "SingleFlight",
    "CacheGuard",
    "logger",
    "FileChange",
    "SnapshotInfo",
    "DiffResult",
    "ChangeTracker",
    "logger",
    "DEFAULT_AGENTS",
    "BreakerState",
    "BreakerEntry",
    "FailoverChain",
    "FailoverResult",
    "CircuitBreaker",
    "logger",
    "MutationResult",
    "ConfigMutator",
    "logger",
    "ErrorEvent",
    "Hotspot",
    "PromotedRule",
    "ErrorLedger",
    "MaopResult",
    "new_result",
    "logger",
    "EventPriority",
    "AckStatus",
    "Event",
    "DeadLetterEntry",
    "SyncHandler",
    "AsyncHandler",
    "Handler",
    "EventBus",
    "get_event_bus",
    "T",
    "logger",
    "ORPHAN_THRESHOLD_S",
    "with_file_lock",
    "FileLock",
    "logger",
    "ROTATE_EXTENSIONS",
    "RotateResult",
    "LogRotateConfig",
    "rotate_logs",
    "LogRotateScheduler",
    "logger",
    "EnqueueError",
    "MessagePriority",
    "Message",
    "DeadLetterMessage",
    "QueueStats",
    "MessageQueue",
    "logger",
    "StepCheckpoint",
    "RunState",
    "PipelineCheckpoint",
    "PreemptableWorkerPool",
    "PriorityTask",
    "PriorityTaskQueue",
    "logger",
    "RateLimitResult",
    "RateLimiterConfig",
    "TokenBucket",
    "SlidingWindow",
    "RateLimiter",
    "safe_write_bytes",
    "safe_write_json",
    "safe_write_text",
    "logger",
    "HealAction",
    "HealStatus",
    "HealRule",
    "HealResult",
    "HealReport",
    "SelfHealEngine",
    "logger",
    "ServiceContainer",
    "logger",
    "SubprocessStreamer",
    "StreamRegistry",
    "get_stream_registry",
    "logger",
    "WorkerStatus",
    "WorkerTask",
    "PoolStats",
    "WorkerPool",
    "get_worker_pool",
]

# 符号 → 子模块名映射（惰性加载用，含私有符号）
_SYMBOL_TO_MODULE: dict[str, str] = {
    # 注: 多个子模块均导出同名符号（如 logger），
    # 按字典构造语义仅最后一个映射生效，与重构前运行时行为一致。
    "_SINGLEFLIGHT_WAIT_TIMEOUT_S": "cache",
    "K": "cache",
    "V": "cache",
    "_SentinelNull": "cache",
    "SENTINEL_NULL": "cache",
    "is_sentinel_null": "cache",
    "CacheEntry": "cache",
    "CacheStats": "cache",
    "LRUCache": "cache",
    "_caches": "cache",
    "_caches_lock": "cache",
    "get_cache": "cache",
    "CacheGuardConfig": "cache",
    "CacheGuardStats": "cache",
    "SingleFlight": "cache",
    "CacheGuard": "cache",
    "FileChange": "change_tracker",
    "SnapshotInfo": "change_tracker",
    "DiffResult": "change_tracker",
    "ChangeTracker": "change_tracker",
    "DEFAULT_AGENTS": "circuit_breaker",
    "BreakerState": "circuit_breaker",
    "BreakerEntry": "circuit_breaker",
    "FailoverChain": "circuit_breaker",
    "FailoverResult": "circuit_breaker",
    "_BREAKER_DDL": "circuit_breaker",
    "CircuitBreaker": "circuit_breaker",
    "MutationResult": "config_mutator",
    "ConfigMutator": "config_mutator",
    "ErrorEvent": "error_ledger",
    "Hotspot": "error_ledger",
    "PromotedRule": "error_ledger",
    "_ERROR_LEDGER_DDL": "error_ledger",
    "ErrorLedger": "error_ledger",
    "_TRACE_ID_RE": "error_schema",
    "MaopResult": "error_schema",
    "new_result": "error_schema",
    "_DEFAULT_MAX_HISTORY": "event_bus",
    "_DEFAULT_MAX_DEAD_LETTERS": "event_bus",
    "EventPriority": "event_bus",
    "AckStatus": "event_bus",
    "Event": "event_bus",
    "DeadLetterEntry": "event_bus",
    "SyncHandler": "event_bus",
    "AsyncHandler": "event_bus",
    "Handler": "event_bus",
    "_Subscription": "event_bus",
    "EventBus": "event_bus",
    "_global_bus": "event_bus",
    "_global_bus_lock": "event_bus",
    "get_event_bus": "event_bus",
    "T": "filelock",
    "ORPHAN_THRESHOLD_S": "filelock",
    "_lock_path": "filelock",
    "_is_orphan": "filelock",
    "_write_lock_content": "filelock",
    "with_file_lock": "filelock",
    "FileLock": "filelock",
    "ROTATE_EXTENSIONS": "log_rotate",
    "_ROTATED_RE": "log_rotate",
    "RotateResult": "log_rotate",
    "LogRotateConfig": "log_rotate",
    "_compress_file": "log_rotate",
    "_rotate_file": "log_rotate",
    "_cleanup_old_rotations": "log_rotate",
    "rotate_logs": "log_rotate",
    "LogRotateScheduler": "log_rotate",
    "EnqueueError": "message_queue",
    "_QUEUE_DDL": "message_queue",
    "MessagePriority": "message_queue",
    "Message": "message_queue",
    "DeadLetterMessage": "message_queue",
    "QueueStats": "message_queue",
    "MessageQueue": "message_queue",
    "StepCheckpoint": "pipeline_checkpoint",
    "RunState": "pipeline_checkpoint",
    "_CHECKPOINT_DDL": "pipeline_checkpoint",
    "PipelineCheckpoint": "pipeline_checkpoint",
    "PreemptableWorkerPool": "preemptable_worker_pool",
    "PriorityTask": "priority_queue",
    "PriorityTaskQueue": "priority_queue",
    "RateLimitResult": "rate_limiter",
    "RateLimiterConfig": "rate_limiter",
    "TokenBucket": "rate_limiter",
    "SlidingWindow": "rate_limiter",
    "RateLimiter": "rate_limiter",
    "safe_write_bytes": "safe_writer",
    "safe_write_json": "safe_writer",
    "safe_write_text": "safe_writer",
    "_fsync_dir": "safe_writer",
    "HealAction": "self_heal",
    "HealStatus": "self_heal",
    "HealRule": "self_heal",
    "HealResult": "self_heal",
    "HealReport": "self_heal",
    "_SELF_HEAL_DDL": "self_heal",
    "SelfHealEngine": "self_heal",
    "ServiceContainer": "services",
    "_ANSI_RE": "streaming",
    "SubprocessStreamer": "streaming",
    "StreamRegistry": "streaming",
    "_registry": "streaming",
    "get_stream_registry": "streaming",
    "logger": "worker_pool",
    "WorkerStatus": "worker_pool",
    "WorkerTask": "worker_pool",
    "PoolStats": "worker_pool",
    "WorkerPool": "worker_pool",
    "_global_pool": "worker_pool",
    "get_worker_pool": "worker_pool",
}


def __getattr__(name: str):
    """惰性加载子模块符号，避免循环导入。"""
    if name in _SYMBOL_TO_MODULE:
        mod_name = _SYMBOL_TO_MODULE[name]
        mod = importlib.import_module(f".{mod_name}", __name__)
        value = getattr(mod, name)
        globals()[name] = value  # 缓存，下次直接访问
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
