"""Backends subpackage.

可插拔后端（存储/缓存/队列/KV）+ 数据访问层 + 数据库迁移。

Modules:
    backends, backends_distributed, backends_redis, backends_vault,
    backends_pg, backends_rabbitmq, data, db_utils, db_backup,
    artifact_store, image_store, kv_store, migration
"""
from __future__ import annotations

import importlib

__all__ = [
    "ALLOWED_EXTENSIONS",
    "DEFAULT_DATABASES",
    "DEFAULT_RETENTION",
    "MAX_IMAGE_SIZE",
    "SCHEMA_DDL",
    "AlembicBridge",
    "ArtifactInfo",
    "ArtifactStore",
    "ArtifactVersion",
    "BackupEntry",
    "BackupStats",
    "CASResult",
    "CacheBackend",
    "CheckpointRecord",
    "ConnectionPool",
    "DbBackup",
    "DelegationRecord",
    "ErrorLogRecord",
    "EtcdKVBackend",
    "ImageMeta",
    "ImageStore",
    "KVBackend",
    "KVEntry",
    "KVStats",
    "KVStore",
    "LocalSecretBackend",
    "MaopDatabase",
    "MemoryCacheBackend",
    "Migration",
    "MigrationManager",
    "MigrationRecord",
    "PostgreSQLStorageBackend",
    "QueueBackend",
    "RabbitMQQueueBackend",
    "RedisCacheBackend",
    "RedisDistributedLock",
    "RedisQueueBackend",
    "SQLiteKVBackend",
    "SQLiteQueueBackend",
    "SQLiteStorageBackend",
    "SecretBackend",
    "StorageBackend",
    "VaultSecretBackend",
    "cache_delete",
    "cache_get",
    "cache_set",
    "find_project_root",
    "get_cache_backend",
    "get_db_path",
    "get_kv_backend",
    "get_migration_backend",
    "get_pool",
    "get_queue_backend",
    "get_secret_backend",
    "get_storage_backend",
    "kv_get",
    "kv_set",
    "logger",
    "queue_consume",
    "queue_publish",
    "reset_backends",
    "secret_get",
    "secret_set",
    "sqlite_connect",
    "storage_execute",
    "storage_fetchall",
    "storage_fetchone",
    "unified_db_path",
    "validate_identifier",
]

# 符号 → 子模块名映射（惰性加载用，含私有符号）
_SYMBOL_TO_MODULE: dict[str, str] = {
    # 注: 多个子模块均导出同名符号（如 logger），
    # 按字典构造语义仅最后一个映射生效，与重构前运行时行为一致。
    "ArtifactVersion": "artifact_store",
    "ArtifactInfo": "artifact_store",
    "ArtifactStore": "artifact_store",
    "StorageBackend": "backends",
    "SQLiteStorageBackend": "backends",
    "CacheBackend": "backends",
    "MemoryCacheBackend": "backends",
    "QueueBackend": "backends",
    "SQLiteQueueBackend": "backends",
    "KVBackend": "backends",
    "SQLiteKVBackend": "backends",
    "SecretBackend": "backends",
    "LocalSecretBackend": "backends",
    "_storage": "backends",
    "_cache": "backends",
    "_queue": "backends",
    "_kv": "backends",
    "_secret": "backends",
    "_edition_defaults": "backends",
    "get_storage_backend": "backends",
    "get_cache_backend": "backends",
    "get_queue_backend": "backends",
    "get_kv_backend": "backends",
    "get_secret_backend": "backends",
    "reset_backends": "backends",
    "storage_execute": "backends",
    "storage_fetchone": "backends",
    "storage_fetchall": "backends",
    "cache_get": "backends",
    "cache_set": "backends",
    "cache_delete": "backends",
    "queue_publish": "backends",
    "queue_consume": "backends",
    "kv_get": "backends",
    "kv_set": "backends",
    "secret_get": "backends",
    "secret_set": "backends",
    "_DEFAULT_ETCD_HOST": "backends_distributed",
    "_DEFAULT_ETCD_PORT": "backends_distributed",
    "_DEFAULT_NAMESPACE": "backends_distributed",
    "EtcdKVBackend": "backends_distributed",
    "_build_dsn": "backends_pg",
    "PostgreSQLStorageBackend": "backends_pg",
    "_DEFAULT_RABBITMQ_URL": "backends_rabbitmq",
    "_DLX_EXCHANGE": "backends_rabbitmq",
    "RabbitMQQueueBackend": "backends_rabbitmq",
    "_build_redis_kwargs": "backends_redis",
    "RedisCacheBackend": "backends_redis",
    "RedisQueueBackend": "backends_redis",
    "_RELEASE_LOCK_SCRIPT": "backends_redis",
    "RedisDistributedLock": "backends_redis",
    "VaultSecretBackend": "backends_vault",
    "SCHEMA_DDL": "data",
    "DelegationRecord": "data",
    "CheckpointRecord": "data",
    "ErrorLogRecord": "data",
    "_default_db_path": "data",
    "MaopDatabase": "data",
    "BackupEntry": "db_backup",
    "BackupStats": "db_backup",
    "DEFAULT_DATABASES": "db_backup",
    "DEFAULT_RETENTION": "db_backup",
    "DbBackup": "db_backup",
    "_VALID_IDENTIFIER": "db_utils",
    "_get_busy_timeout_ms": "db_utils",
    "validate_identifier": "db_utils",
    "sqlite_connect": "db_utils",
    "find_project_root": "db_utils",
    "ConnectionPool": "db_utils",
    "_pools": "db_utils",
    "_pools_lock": "db_utils",
    "get_pool": "db_utils",
    "_UNIFIED_DB_NAME": "db_utils",
    "unified_db_path": "db_utils",
    "get_db_path": "db_utils",
    "_resolve_data_dir": "db_utils",
    "ALLOWED_EXTENSIONS": "image_store",
    "MAX_IMAGE_SIZE": "image_store",
    "ImageMeta": "image_store",
    "ImageStore": "image_store",
    "KVEntry": "kv_store",
    "KVStats": "kv_store",
    "CASResult": "kv_store",
    "KVStore": "kv_store",
    "logger": "migration",
    "Migration": "migration",
    "MigrationRecord": "migration",
    "MigrationManager": "migration",
    "AlembicBridge": "migration",
    "get_migration_backend": "migration",
}


def __getattr__(name: str):
    """惰性加载子模块符号，避免循环导入。"""
    if name in _SYMBOL_TO_MODULE:
        mod_name = _SYMBOL_TO_MODULE[name]
        mod = importlib.import_module(f".{mod_name}", __name__)
        value = getattr(mod, name)
        globals()[name] = value  # 缓存，下次直接访问
        return value
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
