"""MAOP MCP Cache — LRU + TTL cache for MCP tool call results.

Phase δ-5: caches successful MCP tool invocations keyed by
``(server_id, tool_name, arguments_hash)`` to avoid redundant calls to
external MCP servers.

Caching policy
--------------
  * Only successful results are cached — a result dict carrying an
    ``error`` key, ``isError: True`` or ``is_error: True`` is skipped.
  * Results explicitly marked ``_mcp_nocache: true`` are never cached,
    letting individual tools opt out (e.g. for side-effecting calls).
  * Default TTL: 300 s (5 minutes). Per-entry TTL override via ``put``.
  * LRU eviction when ``max_entries`` is reached.

The cache is thread-safe (``threading.Lock``) and synchronous — matching
the contract of :mod:`maop.core.cache`. The async ``MCPHub`` wraps cache
checks in the ``call_tool`` hot path without additional locking.

Usage::

    from maop.core.mcp_cache import MCPCache, MCPCacheKey

    cache = MCPCache(max_entries=256, default_ttl_s=300.0)
    key = MCPCacheKey.from_arguments("srv1", "read_file", {"path": "/tmp/x"})
    cache.put(key, {"content": [...], "is_error": False})
    cached = cache.get(key)  # returns the dict, or None on miss/expiry
"""
from __future__ import annotations

import hashlib
import json
import logging
import threading
import time
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)


# ── Keys ───────────────────────────────────────────────────────


@dataclass(frozen=True)
class MCPCacheKey:
    """Cache key for an MCP tool call.

    Hash and equality are derived from ``(server_id, tool_name,
    arguments_hash)`` so instances are safe in dicts and sets.
    ``arguments_hash`` is the SHA-256 hex digest of
    ``json.dumps(arguments, sort_keys=True)``; build keys via
    :meth:`from_arguments` to compute the hash correctly.
    """

    server_id: str
    tool_name: str
    arguments_hash: str

    @classmethod
    def from_arguments(
        cls,
        server_id: str,
        tool_name: str,
        arguments: dict[str, Any] | None,
    ) -> "MCPCacheKey":
        """Build a key from raw arguments, computing the SHA-256 hash.

        ``arguments`` is serialised with ``sort_keys=True`` so dict key
        order does not affect the hash. Non-JSON-native values fall back
        to ``str()`` via ``default=str``.
        """
        payload = json.dumps(arguments or {}, sort_keys=True, default=str)
        digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
        return cls(server_id=server_id, tool_name=tool_name, arguments_hash=digest)

    # __hash__ and __eq__ are auto-generated by frozen=True, but we
    # declare them explicitly to document the contract (and to satisfy
    # the Phase δ-5 spec that calls for both).
    def __hash__(self) -> int:  # noqa: D401 - explicit re-declaration
        return hash((self.server_id, self.tool_name, self.arguments_hash))

    def __eq__(self, other: Any) -> bool:
        if not isinstance(other, MCPCacheKey):
            return NotImplemented
        return (
            self.server_id == other.server_id
            and self.tool_name == other.tool_name
            and self.arguments_hash == other.arguments_hash
        )


# ── Entries ────────────────────────────────────────────────────


@dataclass
class MCPCacheEntry:
    """A single cached MCP tool result."""

    result: dict[str, Any]
    created_at: float
    ttl_s: float
    access_count: int = 0

    def is_expired(self) -> bool:
        """Return True if this entry has exceeded its TTL.

        ``ttl_s <= 0`` means "never expires".
        """
        if self.ttl_s <= 0:
            return False
        return (time.time() - self.created_at) > self.ttl_s


# ── Stats ──────────────────────────────────────────────────────


@dataclass
class MCPCacheStats:
    """Snapshot of cache counters."""

    hits: int = 0
    misses: int = 0
    size: int = 0
    evictions: int = 0


# ── Cache ──────────────────────────────────────────────────────


class MCPCache:
    """LRU + TTL cache for MCP tool call results.

    Parameters
    ----------
    max_entries:
        Maximum number of cached entries. The least-recently-used entry
        is evicted when this is exceeded.
    default_ttl_s:
        Default time-to-live in seconds. 0 = never expires.
    """

    def __init__(
        self,
        max_entries: int = 256,
        default_ttl_s: float = 300.0,
    ) -> None:
        self._max_entries = max(1, max_entries)
        self._default_ttl = default_ttl_s
        self._store: OrderedDict[MCPCacheKey, MCPCacheEntry] = OrderedDict()
        self._lock = threading.Lock()
        self._hits = 0
        self._misses = 0
        self._evictions = 0

    # ── Cacheability check ─────────────────────────────────────

    @staticmethod
    def is_cacheable(result: dict[str, Any]) -> bool:
        """Return True if ``result`` may be cached.

        A result is cacheable when:
          * it has no ``error`` key,
          * ``isError`` / ``is_error`` are not True,
          * it is not explicitly marked ``_mcp_nocache: true``.
        """
        if not isinstance(result, dict):
            return False
        if result.get("_mcp_nocache") is True:
            return False
        if result.get("error"):
            return False
        if result.get("isError") is True:
            return False
        if result.get("is_error") is True:
            return False
        return True

    # ── Core operations ────────────────────────────────────────

    def get(self, key: MCPCacheKey) -> dict[str, Any] | None:
        """Look up a cached result.

        Returns the stored result dict on hit, or ``None`` on miss /
        expiry. Hits update the LRU ordering and bump ``access_count``.
        """
        with self._lock:
            entry = self._store.get(key)
            if entry is None:
                self._misses += 1
                return None
            if entry.is_expired():
                # Expired — drop and count as miss.
                del self._store[key]
                self._misses += 1
                return None
            entry.access_count += 1
            self._store.move_to_end(key)
            self._hits += 1
            return entry.result

    def put(
        self,
        key: MCPCacheKey,
        result: dict[str, Any],
        ttl_s: float | None = None,
    ) -> None:
        """Store a result if it is cacheable.

        Non-cacheable results (errors / ``_mcp_nocache``) are silently
        skipped — callers do not need to pre-check with
        :meth:`is_cacheable`. If the cache is at capacity, the
        least-recently-used entry is evicted.
        """
        if not self.is_cacheable(result):
            return

        effective_ttl = self._default_ttl if ttl_s is None else ttl_s
        now = time.time()

        with self._lock:
            # Re-insert at end if key exists.
            if key in self._store:
                del self._store[key]
            else:
                # Evict LRU when at capacity.
                while len(self._store) >= self._max_entries:
                    evicted_key, _ = self._store.popitem(last=False)
                    self._evictions += 1
                    self._record_eviction()

            self._store[key] = MCPCacheEntry(
                result=result,
                created_at=now,
                ttl_s=effective_ttl,
            )

    def invalidate(
        self,
        server_id: str,
        tool_name: str | None = None,
    ) -> int:
        """Invalidate cached entries.

        If ``tool_name`` is None, all entries for ``server_id`` are
        dropped; otherwise only entries matching both ``server_id`` and
        ``tool_name``. Returns the number of entries removed.
        """
        with self._lock:
            if tool_name is None:
                keys_to_remove = [k for k in self._store if k.server_id == server_id]
            else:
                keys_to_remove = [
                    k
                    for k in self._store
                    if k.server_id == server_id and k.tool_name == tool_name
                ]
            for k in keys_to_remove:
                del self._store[k]
            return len(keys_to_remove)

    def clear(self) -> None:
        """Remove all cached entries."""
        with self._lock:
            self._store.clear()

    def stats(self) -> MCPCacheStats:
        """Return a snapshot of hit / miss / size / eviction counters."""
        with self._lock:
            return MCPCacheStats(
                hits=self._hits,
                misses=self._misses,
                size=len(self._store),
                evictions=self._evictions,
            )

    # ── Helpers ────────────────────────────────────────────────

    def _record_eviction(self) -> None:
        """Increment the global eviction metric (defensive import)."""
        try:
            from maop.core.monitoring import MAOP_MCP_CACHE_EVICTION_TOTAL
        except Exception:
            return
        MAOP_MCP_CACHE_EVICTION_TOTAL.inc()
