"""MAOP Routing Decision Trace — persistent record of scheduling decisions.

Phase γ-4: the scheduling subsystem (RouteScorer / LoadBalancer /
ModelSelector / Dispatcher) emits two parallel kinds of telemetry:

1. **OpenTelemetry spans** (handled in each subsystem's module via
   :func:`maop.core.otel.span`) — exported to the OTel backend for
   distributed trace visualisation.
2. **Routing decision records** (this module) — a SQLite-backed audit
   trail that the dashboard exposes via ``/api/routing/decisions/*`` so
   operators can answer "why was agent X / model Y picked for trace Z?"
   without needing a full OTel backend.

The two layers are complementary: OTel spans carry the high-resolution
parent-child timeline, while the decision store keeps a low-cardinality
human-readable explanation that survives span retention windows.

Each :class:`RoutingDecisionRecord` carries the MAOP ``trace_id`` so the
full Plan → Route → LB → ModelSelect chain can be reconstructed by
querying ``query_by_trace(trace_id)`` even when OTel is disabled (the
default). ``span_id`` / ``parent_span_id`` are populated from the active
OTel span context when available, and left empty/None otherwise — they
are correlation metadata, not foreign keys.

Persistence uses SQLite via :func:`maop.core.db_utils.get_db_path` so
the table lands in the same ``maop.db`` (or per-module file under
``MAOP_DB_PER_MODULE=1``) as the rest of the system. The schema is
idempotent — ``CREATE TABLE IF NOT EXISTS`` — so the store can be
constructed repeatedly without migration.

Usage::

    from maop.core.routing_decision import (
        RoutingDecisionRecord, RoutingDecisionStore,
    )
    import time

    store = RoutingDecisionStore()
    store.record(RoutingDecisionRecord(
        trace_id="abc123",
        span_id="",
        parent_span_id=None,
        timestamp=time.time(),
        stage="route_scorer",
        input_summary={"routing_key": "codegen", "candidate_count": 3},
        output_summary={"selected_agent": "claude", "score": 0.85},
        explanation="Selected agent 'claude' with confidence 0.85 (high) ...",
        duration_ms=1.2,
        attributes={"decision_mode": "weighted_sum"},
    ))

    chain = store.query_by_trace("abc123")
    removed = store.prune(older_than_days=7)
"""

from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from maop.core.db_utils import get_db_path, sqlite_connect

logger = logging.getLogger(__name__)


# ── Data model ─────────────────────────────────────────────────


@dataclass
class RoutingDecisionRecord:
    """A single scheduling decision made by one of the routing subsystems.

    Attributes
    ----------
    trace_id:
        MAOP trace identifier (also injected as ``maop.trace_id`` OTel
        span attribute). This is the primary key for reconstructing the
        full Plan → Route → LB → ModelSelect chain.
    span_id:
        OTel span ID of the span that recorded this decision. Empty
        string when OTel is disabled (the default).
    parent_span_id:
        OTel span ID of the parent span, when known. ``None`` when the
        decision was made outside any OTel span context.
    timestamp:
        Unix epoch seconds (UTC) — same convention as
        :class:`maop.core.mcp_audit.MCPAuditRecord`.
    stage:
        Which subsystem made the decision. One of
        ``"route_scorer"`` / ``"load_balancer"`` / ``"model_selector"``
        / ``"dispatcher"``.
    input_summary:
        Low-cardinality dict describing the decision input (e.g.
        ``{"routing_key": "codegen", "candidate_count": 3}``).
        Full input data is intentionally NOT stored — only key
        identifiers needed to correlate and explain the decision.
    output_summary:
        Low-cardinality dict describing the decision output (e.g.
        ``{"selected_agent": "claude", "score": 0.85}``).
    explanation:
        Human-readable decision explanation string. Generated by each
        subsystem to surface the "why" in plain English.
    duration_ms:
        Wall-clock decision duration in milliseconds.
    attributes:
        Additional OTel span attributes (e.g. ``decision_mode``,
        ``sticky_session_hit``). Stored as JSON for flexibility.
    """

    trace_id: str
    span_id: str
    parent_span_id: str | None
    timestamp: float
    stage: str
    input_summary: dict[str, Any] = field(default_factory=dict)
    output_summary: dict[str, Any] = field(default_factory=dict)
    explanation: str = ""
    duration_ms: float = 0.0
    attributes: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dict (for API responses)."""
        return {
            "trace_id": self.trace_id,
            "span_id": self.span_id,
            "parent_span_id": self.parent_span_id,
            "timestamp": self.timestamp,
            "stage": self.stage,
            "input_summary": dict(self.input_summary),
            "output_summary": dict(self.output_summary),
            "explanation": self.explanation,
            "duration_ms": self.duration_ms,
            "attributes": dict(self.attributes),
        }


# ── DDL ────────────────────────────────────────────────────────


_ROUTING_DECISION_DDL = """
CREATE TABLE IF NOT EXISTS routing_decisions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    trace_id TEXT NOT NULL,
    span_id TEXT NOT NULL,
    parent_span_id TEXT,
    timestamp REAL NOT NULL,
    stage TEXT NOT NULL,
    input_summary TEXT,
    output_summary TEXT,
    explanation TEXT,
    duration_ms REAL,
    attributes TEXT
);
CREATE INDEX IF NOT EXISTS idx_rd_trace ON routing_decisions(trace_id);
CREATE INDEX IF NOT EXISTS idx_rd_ts ON routing_decisions(timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_rd_stage ON routing_decisions(stage);
"""


# ── Store ──────────────────────────────────────────────────────


class RoutingDecisionStore:
    """SQLite-backed store for :class:`RoutingDecisionRecord` entries.

    Parameters
    ----------
    db_path:
        Optional explicit database path. When omitted, the path is
        resolved via :func:`maop.core.db_utils.get_db_path("routing_decisions")`
        so it follows the same unified / per-module routing as the rest
        of the codebase. Tests typically pass an in-memory or temp path
        to isolate themselves from the production DB.
    """

    def __init__(self, db_path: Path | str | None = None) -> None:
        if db_path is None:
            db_path = get_db_path("routing_decisions")
        self._db_path = Path(str(db_path))
        self._db_path.parent.mkdir(parents=True, exist_ok=True)
        self._init_db()

    def _init_db(self) -> None:
        with self._connect() as conn:
            conn.executescript(_ROUTING_DECISION_DDL)

    def _connect(self):
        return sqlite_connect(self._db_path, foreign_keys=False)

    # ── Write path ──────────────────────────────────────────────

    def record(self, decision: RoutingDecisionRecord) -> int:
        """Persist a single routing decision. Returns the inserted row id."""
        with self._connect() as conn:
            cursor = conn.execute(
                """INSERT INTO routing_decisions
                   (trace_id, span_id, parent_span_id, timestamp, stage,
                    input_summary, output_summary, explanation, duration_ms,
                    attributes)
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
                (
                    decision.trace_id,
                    decision.span_id,
                    decision.parent_span_id,
                    decision.timestamp,
                    decision.stage,
                    json.dumps(decision.input_summary, default=str,
                                ensure_ascii=False),
                    json.dumps(decision.output_summary, default=str,
                                ensure_ascii=False),
                    decision.explanation,
                    decision.duration_ms,
                    json.dumps(decision.attributes, default=str,
                                ensure_ascii=False),
                ),
            )
            row_id = cursor.lastrowid or 0
        logger.debug(
            "[routing_decision] logged stage=%s trace_id=%s agent=%s",
            decision.stage, decision.trace_id,
            decision.output_summary.get("selected_agent")
            or decision.output_summary.get("selected_model"),
        )
        return row_id

    # ── Read path ───────────────────────────────────────────────

    def query_by_trace(self, trace_id: str) -> list[RoutingDecisionRecord]:
        """Return all decisions for a trace, oldest-first (call order)."""
        if not trace_id:
            return []
        sql = (
            "SELECT * FROM routing_decisions WHERE trace_id = ? "
            "ORDER BY timestamp ASC"
        )
        with self._connect() as conn:
            cursor = conn.execute(sql, (trace_id,))
            rows = cursor.fetchall()
        return [self._row_to_record(r) for r in rows]

    def query_recent(
        self,
        limit: int = 100,
        stage: str | None = None,
    ) -> list[RoutingDecisionRecord]:
        """Return recent decisions, newest-first."""
        sql = "SELECT * FROM routing_decisions"
        params: list[Any] = []
        if stage:
            sql += " WHERE stage = ?"
            params.append(stage)
        sql += " ORDER BY timestamp DESC LIMIT ?"
        params.append(max(0, int(limit)))
        with self._connect() as conn:
            cursor = conn.execute(sql, params)
            rows = cursor.fetchall()
        return [self._row_to_record(r) for r in rows]

    def count(self, stage: str | None = None) -> int:
        """Total decision count, optionally filtered by stage."""
        sql = "SELECT COUNT(*) FROM routing_decisions"
        params: list[Any] = []
        if stage:
            sql += " WHERE stage = ?"
            params.append(stage)
        with self._connect() as conn:
            row = conn.execute(sql, params).fetchone()
        return int(row[0]) if row else 0

    def stats(self) -> dict[str, Any]:
        """Aggregate stats for the dashboard ``/stats`` endpoint."""
        with self._connect() as conn:
            total_row = conn.execute(
                "SELECT COUNT(*) FROM routing_decisions"
            ).fetchone()
            total = int(total_row[0]) if total_row else 0

            stage_rows = conn.execute(
                "SELECT stage, COUNT(*) FROM routing_decisions "
                "GROUP BY stage"
            ).fetchall()
            by_stage = {r[0]: int(r[1]) for r in stage_rows}

            cutoff = time.time() - 86400.0
            last_24h_row = conn.execute(
                "SELECT COUNT(*) FROM routing_decisions WHERE timestamp >= ?",
                (cutoff,),
            ).fetchone()
            last_24h = int(last_24h_row[0]) if last_24h_row else 0
        return {
            "total": total,
            "by_stage": by_stage,
            "last_24h": last_24h,
        }

    def prune(self, older_than_days: int = 7) -> int:
        """Delete records older than ``older_than_days``.

        Default retention is 7 days (shorter than ``mcp_audit``'s 30
        days) because routing decisions are high-volume — operators
        typically only need the recent window for debugging.
        """
        cutoff = time.time() - (max(0, int(older_than_days)) * 86400)
        with self._connect() as conn:
            cursor = conn.execute(
                "DELETE FROM routing_decisions WHERE timestamp < ?",
                (cutoff,),
            )
            removed = cursor.rowcount
        logger.info(
            "[routing_decision] pruned %d records older than %d days",
            removed, older_than_days,
        )
        return int(removed)

    # ── Helpers ─────────────────────────────────────────────────

    @staticmethod
    def _row_to_record(row: Any) -> RoutingDecisionRecord:
        """Convert a sqlite3.Row to a RoutingDecisionRecord."""
        # sqlite3.Row supports both index and key access.
        def _get(key: str, default: Any = None) -> Any:
            try:
                return row[key]
            except (KeyError, IndexError, TypeError):
                return default

        def _loads(value: Any, default: Any) -> dict[str, Any]:
            if not value:
                return default
            try:
                return json.loads(value)
            except (TypeError, ValueError):
                return default

        return RoutingDecisionRecord(
            trace_id=str(_get("trace_id", "") or ""),
            span_id=str(_get("span_id", "") or ""),
            parent_span_id=_get("parent_span_id"),
            timestamp=float(_get("timestamp", 0.0) or 0.0),
            stage=str(_get("stage", "") or ""),
            input_summary=_loads(_get("input_summary"), {}),
            output_summary=_loads(_get("output_summary"), {}),
            explanation=str(_get("explanation", "") or ""),
            duration_ms=float(_get("duration_ms", 0.0) or 0.0),
            attributes=_loads(_get("attributes"), {}),
        )


# ── OTel span context helpers ──────────────────────────────────


def get_active_span_context() -> tuple[str, str, str | None]:
    """Return ``(trace_id, span_id, parent_span_id)`` for the active span.

    When OpenTelemetry is unavailable or no span is active, returns
    ``("", "", None)``. Callers should treat empty strings as "not in
    an OTel context" and fall back to the MAOP ``trace_id`` they
    already have.

    The ``parent_span_id`` is extracted from the active span's parent
    (``span.parent.span_id``) so children of a dispatcher span can
    record who their parent was — useful when reconstructing the chain
    from the SQLite store alone.
    """
    try:
        from opentelemetry.trace import get_current_span
        span = get_current_span()
        ctx = span.get_span_context()
        if ctx is None or not getattr(ctx, "is_valid", False):
            return ("", "", None)
        trace_id = format(ctx.trace_id, "032x")
        span_id = format(ctx.span_id, "016x")
        parent_span_id: str | None = None
        parent = getattr(span, "parent", None)
        if parent is not None:
            try:
                parent_span_id = format(parent.span_id, "016x")
            except (AttributeError, TypeError):
                parent_span_id = None
        return (trace_id, span_id, parent_span_id)
    except Exception:
        return ("", "", None)


# ── Module-level singleton (lazy) ──────────────────────────────


_store_instance: RoutingDecisionStore | None = None


def get_routing_decision_store() -> RoutingDecisionStore:
    """Get or lazily create the module-level :class:`RoutingDecisionStore`.

    The store is cheap to construct (single ``CREATE TABLE IF NOT
    EXISTS``) but reusing a single instance avoids repeated DDL round
    trips in hot paths. Tests that need isolation should construct
    their own :class:`RoutingDecisionStore` with a temp ``db_path``
    rather than calling this helper.
    """
    global _store_instance
    if _store_instance is None:
        _store_instance = RoutingDecisionStore()
    return _store_instance


def reset_routing_decision_store() -> None:
    """Reset the module-level singleton (for tests)."""
    global _store_instance
    _store_instance = None


def record_decision_safe(
    decision: RoutingDecisionRecord,
    *,
    store: RoutingDecisionStore | None = None,
) -> None:
    """Best-effort :meth:`RoutingDecisionStore.record` wrapper.

    Scheduling subsystems call this from inside their OTel span block
    so the decision is recorded even when OTel itself is disabled. Any
    SQLite error is logged at debug level and swallowed — recording
    must never break the actual routing decision.

    When ``decision.trace_id`` is empty the call is a no-op: without a
    trace id the record cannot be correlated to a Plan → Route → LB →
    ModelSelect chain, so it has no audit value. This also avoids
    adding SQLite I/O latency to non-instrumented hot paths (e.g.
    ``LoadBalancer.select`` calls that originate from tests or legacy
    code paths without a trace id).
    """
    if not decision.trace_id:
        return
    try:
        target = store or get_routing_decision_store()
        target.record(decision)
    except Exception as exc:
        logger.debug("[routing_decision] record failed (non-fatal): %s", exc)
